services:

  nginx:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
      mongo:
        condition: service_healthy
    networks:
      - app-network
    mem_limit: 256m
    cpus: 0.25

  frontend:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.frontend
    container_name: frontend
    env_file:
      - ../../env/development.env
    volumes:
      - ../../frontend:/frontend
      - frontend-node-modules:/frontend/node_modules
    expose:
      - "5173"
    networks:
      - app-network
    mem_limit: 1g
    cpus: 0.5

  backend:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile.backend
    container_name: backend
    env_file:
      - ../../env/development.env
    volumes:
      - ../../backend:/backend
      - backend-node-modules:/backend/node_modules
    expose:
      - "5000"
    networks:
      - app-network
    mem_limit: 1g
    cpus: 0.5

  mongo:
    image: mongo:8.0.19
    container_name: mongodb
    env_file:
      - ../../env/development.env
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    networks:
      - app-network
    mem_limit: 2g
    cpus: 1
    healthcheck:
      test: ["CMD-SHELL", "mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

volumes:
  mongo-data:
  frontend-node-modules:
  backend-node-modules:

networks:
  app-network:
    driver: bridge